---

# -----------------
# Control variables (Travis Settings)
# -----------------
#
# PUBLISH_IMAGES    Should be 'yes' to enable publishing to Docker Hub.
#
# If you set PUBLISH_IMAGES you must also set the following: -
#
# DOCKER_USERNAME   If PUBLISH_IMAGES is 'yes'
# DOCKER_PASSWORD   If PUBLISH_IMAGES is 'yes'
#
# You control the Stack container's source and destination image names with...
#
# BE_NAMESPACE      To over-ride the default namespace of the source backend
#                   image (which is 'xchem')
# BE_IMAGE_TAG      To over-ride the default tag of the source backend
#                   (which is 'latest')
# LOADER_NAMESPACE  To over-ride the default namespace of the produced
#                   loader container image (which is 'xchem')

os: linux
services:
- docker

stages:
- name: build
- name: build stable
  if: |
    tag IS present \
    AND tag =~ ^([0-9]+\.){1,2}[0-9]+$ \
    AND env(PUBLISH_IMAGES) = yes

before_install:
- export LOADER_NAMESPACE=${LOADER_NAMESPACE-xchem}
- export BE_NAMESPACE=${BE_NAMESPACE-xchem}
- export BE_IMAGE_TAG=${BE_IMAGE_TAG-latest}

before_script:
- echo ${BE_NAMESPACE}
- echo ${BE_IMAGE_TAG}
- echo ${LOADER_NAMESPACE}
- echo ${PUBLISH_IMAGES}
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

jobs:
  include:

  # Published (pushed) images...
  #
  # Every successful master build results in a latest image
  # and every tag results in a tagged image.
  # Tags that match a RegEx are considered 'official' releases
  # and also result in a 'stable' image.

  - stage: build
    name: Latest Container
    script:
    # The core loader
    - docker build -t ${LOADER_NAMESPACE}/fragalysis-loader:latest --build-arg BE_NAMESPACE=${BE_NAMESPACE} --build-arg BE_IMAGE_TAG=${BE_IMAGE_TAG} .
    - docker push ${LOADER_NAMESPACE}/fragalysis-loader:latest

    # The mount loader (expects an NFS export to mount to)
    - pushd specialised-loaders/mount-loader
    - docker build -t ${LOADER_NAMESPACE}/fragalysis-mount-loader:latest --build-arg BE_NAMESPACE=${BE_NAMESPACE} --build-arg BE_IMAGE_TAG=${BE_IMAGE_TAG} .
    - docker push ${LOADER_NAMESPACE}/fragalysis-mount-loader:latest
    - popd

    # The s3 loader (expects an AWS S3 bucket)
    - pushd specialised-loaders/s3-loader
    - docker build -t ${LOADER_NAMESPACE}/fragalysis-s3-loader:latest --build-arg BE_NAMESPACE=${BE_NAMESPACE} --build-arg BE_IMAGE_TAG=${BE_IMAGE_TAG} .
    - docker push ${LOADER_NAMESPACE}/fragalysis-s3-loader:latest
    - popd

  - stage: build
    name: Tagged Container
    script:
    - docker build -t ${LOADER_NAMESPACE}/fragalysis-loader:${TRAVIS_TAG} --build-arg BE_NAMESPACE=${BE_NAMESPACE} --build-arg BE_IMAGE_TAG=${BE_IMAGE_TAG} .
    - docker push ${LOADER_NAMESPACE}/fragalysis-loader:${TRAVIS_TAG}
    - pushd specialised-loaders/mount-loader
    - docker build -t ${LOADER_NAMESPACE}/fragalysis-mount-loader:${TRAVIS_TAG} --build-arg BE_NAMESPACE=${BE_NAMESPACE} --build-arg BE_IMAGE_TAG=${BE_IMAGE_TAG} .
    - docker push ${LOADER_NAMESPACE}/fragalysis-mount-loader:${TRAVIS_TAG}
    - popd
    - pushd specialised-loaders/s3-loader
    - docker build -t ${LOADER_NAMESPACE}/fragalysis-s3-loader:${TRAVIS_TAG} --build-arg BE_NAMESPACE=${BE_NAMESPACE} --build-arg BE_IMAGE_TAG=${BE_IMAGE_TAG} .
    - docker push ${LOADER_NAMESPACE}/fragalysis-s3-loader:${TRAVIS_TAG}
    - popd
    if: tag IS present AND env(PUBLISH_IMAGES) = yes

  - stage: build stable
    name: Stable Container
    script:
    - docker pull ${LOADER_NAMESPACE}/fragalysis-loader:${TRAVIS_TAG}
    - docker tag ${LOADER_NAMESPACE}/fragalysis-loader:${TRAVIS_TAG} ${LOADER_NAMESPACE}/fragalysis-loader:stable
    - docker push ${LOADER_NAMESPACE}/fragalysis-loader:stable
    - docker pull ${LOADER_NAMESPACE}/fragalysis-mount-loader:${TRAVIS_TAG}
    - docker tag ${LOADER_NAMESPACE}/fragalysis-mount-loader:${TRAVIS_TAG} ${LOADER_NAMESPACE}/fragalysis-mount-loader:stable
    - docker push ${LOADER_NAMESPACE}/fragalysis-mount-loader:stable
    - docker pull ${LOADER_NAMESPACE}/fragalysis-s3-loader:${TRAVIS_TAG}
    - docker tag ${LOADER_NAMESPACE}/fragalysis-s3-loader:${TRAVIS_TAG} ${LOADER_NAMESPACE}/fragalysis-s3-loader:stable
    - docker push ${LOADER_NAMESPACE}/fragalysis-s3-loader:stable
notifications:
  slack: fragalysis:a6ADA8gLyx8tpHQfyzucMB8B
